### ISSUE TITLE
Import fails after upgrade 1.10.40 to latest (1.11.9)

### ISSUE THREAD

**Issue by exeqtwasnotfree** [atrocore/atrocore#1303]
Today I try the latest version on our TEST-server, and after upgrading this versions:
  - Upgrading atrocore/core (1.10.40 => 1.11.9)
  - Upgrading atrocore/export-feeds (1.8.18 => 1.8.41)
  - Upgrading atrocore/import-feeds (1.6.21 => 1.6.33)
  - Upgrading atrocore/pim (1.13.19 => 1.13.35)

When I run any import-job it fails with this error:
```
Message
fputcsv(): Argument #3 ($separator) must be a single character 
```

We use \t as separator in the csv-files, is this the cause?

And several export-job fail with error:
```
Message
Invalid relation metadata 
```
I continue troubleshoot this....

**Comment by exeqtwasnotfree** [comment]
Import seems to work if I change delimiter from \t to ; in my small import-test with one row.

**Comment by exeqtwasnotfree** [comment]
And export seems to fail if there is one or both of 2 field with shared optionlist in it.

**Comment by AnnZast** [comment]
Hello,
Do you mean that the export fails if it has two fields that use the same list?

**Comment by exeqtwasnotfree** [comment]
Yes, what I can find. I have 2 fields that share the same list, and if ether of them is included in the export it fails with "Invalid relation metadata".

**Comment by AnnZast** [comment]
Hello,
As for imports, there is a bug when /t is selected as a separator. It will be fixed in the next release.
Regarding the error in export, I could not reproduce it yet, two fields with the same list were exported successfully. Maybe the reason is something else.

**Comment by AnnZast** [comment]
Hello,
The bug in import with separator \t is already fixed

**Comment by exeqtwasnotfree** [comment]
Thank you for fixing import, it works now in TEST.
The export is still failing on several export-feeds, (4 out of 10 feeds ), but I don´t have the time to make more tests for this right now.

**Comment by AnnZast** [comment]
Hello,

I was able to reproduce the same error with export when exporting field of type multi-value list. We will fix the bug in the next release.

**Comment by AnnZast** [comment]
Hello,
The bug in export is already fixed.

**Comment by exeqtwasnotfree** [comment]
All my issues is fixed with the version we now run. so I close this case now. 
Thank you for the help !
