### ISSUE TITLE
UI field display names and descriptions post update to Core 1.12.20

### ISSUE THREAD

**Issue by jhedup** [atrocore/atrocore#1311]
After the lasted update rounds the UI is mostly displaying technical names. Fields with variables like in Notifications are not displaying correctly as an example:

Notifications List View:
Before: Export has been finished. You can [download link] the file.
After: exportDownloadNotification

Across the board many areas in the UI is not displaying correctly.

**Comment by rdzouk** [comment]
Hello, 
Try to execute this command in your atrocore instance folder :
php index.php refresh translations

**Comment by jhedup** [comment]
Thank you, some improvement in the Messages like notifications but the UI still is all technical names. Fortunately I have access to this server but the other not, should one expect this type of post upgrade steps or would it be normally be handled by the upgrade process?

**Comment by rratsun** [comment]
Hello, the bug was fixed in the latest release. Please update to the core 1.13.2 and above.

**Comment by jhedup** [comment]
I was on 1.13.5 but the issue remained. Fixing it required a reset of the Preferences to Default and then selecting a Style again.
