### ISSUE TITLE
error installing atroPIM and atroDAM with demo data

### ISSUE THREAD

**Issue by clin12345** [atrocore/atrocore#297]
hi...
when im installing with demo data either atroPIM or atroDAM its give me error 500, but if im installing without demo data everything works...is it a bug or im doing something wrong.
i follow your installation instruction
ubuntu 20.04
php 7.4
mysql 5.7

many thanks

**Comment by rratsun** [comment]
Fixed in CORE 1.4.28

**Comment by clin12345** [comment]
hello @rratsun i still get the same error
Failed to load resource: the server responded with a status of 500 (Internal Server Error)                            createAdmin:1

i checked the version its core 1.4.29

thank you

**Comment by rratsun** [comment]
I cannot reproduce the error.
Please, provide me an errors logs. ```data/logs/```

**Comment by clin12345** [comment]
hello @rratsun thank you for your help
i cant find any data/logs/ or log files

this is what i do
#mkdir /var/www/atropim_demo
#cd /var/www/atropim_demo
#git clone https://github.com/atrocore/skeleton-pim.git . && php composer.phar self-update && php composer.phar update
#chown -R www-data:www-data /var/www/atropim_demo
#find . -type d -exec chmod 755 {} + && find . -type f -exec chmod 644 {} +;
#find client data custom uploadCREATE DATABASE atrocore; -type d -exec chmod 775 {} + && find client data custom upload -type f -exec chmod 664 {} +
#crontab -e -u www-data

#mysql -u root -p
CREATE DATABASE atrocore_demo;
CREATE USER 'atrocore_demo_user'@'localhost' IDENTIFIED BY 'atrocore_password';
GRANT ALL ON atrocore_demo.* TO atrocore_demo_user@localhost WITH GRANT OPTION;

then i go to http://localhost
follow the instructions
at the administrator setup page i click finish

inspect
i found error "internal service error 500" 
its give me a link http://localhost/api/v1/Installer/createAdmin

this page isn't working
http error 401

**Comment by clin12345** [comment]
strange after a few hours, data/logs appears
that the error value
[2022-04-20 23:10:01] Log.ERROR: Uncaught Exception TypeError: "Return value of Espo\Core\Utils\Language::detectLanguage() must be of the type string, null returned" at /var/www/atropim_demo/vendor/atrocore/core/app/Espo/Core/Utils/Language.php line 126 {"exception":"[object] (TypeError(code: 0): Return value of Espo\\Core\\Utils\\Language::detectLanguage() must be of the type string, null returned at /var/www/atropim_demo/vendor/atrocore/core/app/Espo/Core/Utils/Language.php:126)"} []

**Comment by rratsun** [comment]
I still cannot reproduce this error. 
Try now, maybe there is no error in new release.

Perhaps, the problem in your environment. Maybe you have different version of PHP for CLI and for WEB, or you have different extensions for different versions of PHP.
